component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: file_main
      name: main
      paths:
        - main.rs
    - component_id: file_lib
      name: lib
      paths:
        - lib.rs
